<!-- Top menu  -->
<table cellspacing="0" cellpadding="0" width="100%" bgcolor="#000000"  background="http://www.splitsbrowser.org.uk/images/uninav_bg.gif" border="0">
   <tbody>
      <tr>
         <td align="right">
            <table cellspacing="3" cellpadding="0" align="right" border="0">
               <tbody>
                  <tr>
                     <td><font face="Verdana,Arial" color="#ffffff" size="1"><a class="nav" href="http://www.splitsbrowser.org.uk/browseevents.php">Results </a>|</font></td>
                     <td><font face="Verdana,Arial" color="#ffffff" size="1"><a class="nav" href="http://www.splitsbrowser.org.uk/addevent.php">Add event </a>|</font></td>
                     <td><font face="Verdana,Arial" color="#ffffff" class="tinyText"><a class="nav" href="http://www.splitsbrowser.org.uk/EventSwitchBoard.php">Event Admin </a>|</font></td> 
                     <td><font face="Verdana,Arial" color="#ffffff" size="1"><a class="nav" href="http://www.splitsbrowser.org.uk/development.shtml">Development </a>|</font></td>
                     <td><font face="Verdana,Arial" color="#ffffff" size="1"><a class="nav" href="mailto:support@splitsbrowser.org.uk">Contact</a></font>&nbsp;</td>
                  </tr>
               </tbody>
            </table>
         </td>
      </tr>
   </tbody>
</table>
<!-- End of top menu  -->
<!-- Splitsbrowser logo  -->
<table cellspacing="0" cellpadding="0" width="100%"  alt="Splitsbrower logo" bgcolor="#ff9900" background="http://www.splitsbrowser.org.uk/images/orange_bg.gif" border="0">
   <tbody>
      <tr>
         <td valign="top" width="211"><a href="http://www.splitsbrowser.org.uk/"><img alt="Splitsbrowser logo" src="http://www.splitsbrowser.org.uk/images/sb.png" border="0" width="211" height="51"></a></td>
         <td valign="bottom" align="right" class="smallText">
            &nbsp;
         </td>
      </tr>
   </tbody>
</table>
<!-- End of splitsbrowser logo  -->

